# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.31

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/lui/Desktop/lavender

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/lui/Desktop/lavender/build

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/opt/homebrew/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/lui/Desktop/lavender/build/CMakeFiles /Users/lui/Desktop/lavender/build//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/lui/Desktop/lavender/build/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named lavender

# Build rule for target.
lavender: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 lavender
.PHONY : lavender

# fast build rule for target.
lavender/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lavender.dir/build.make CMakeFiles/lavender.dir/build
.PHONY : lavender/fast

src/albumMenu.o: src/albumMenu.cpp.o
.PHONY : src/albumMenu.o

# target to build an object file
src/albumMenu.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lavender.dir/build.make CMakeFiles/lavender.dir/src/albumMenu.cpp.o
.PHONY : src/albumMenu.cpp.o

src/albumMenu.i: src/albumMenu.cpp.i
.PHONY : src/albumMenu.i

# target to preprocess a source file
src/albumMenu.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lavender.dir/build.make CMakeFiles/lavender.dir/src/albumMenu.cpp.i
.PHONY : src/albumMenu.cpp.i

src/albumMenu.s: src/albumMenu.cpp.s
.PHONY : src/albumMenu.s

# target to generate assembly for a file
src/albumMenu.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lavender.dir/build.make CMakeFiles/lavender.dir/src/albumMenu.cpp.s
.PHONY : src/albumMenu.cpp.s

src/apiFetch.o: src/apiFetch.cpp.o
.PHONY : src/apiFetch.o

# target to build an object file
src/apiFetch.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lavender.dir/build.make CMakeFiles/lavender.dir/src/apiFetch.cpp.o
.PHONY : src/apiFetch.cpp.o

src/apiFetch.i: src/apiFetch.cpp.i
.PHONY : src/apiFetch.i

# target to preprocess a source file
src/apiFetch.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lavender.dir/build.make CMakeFiles/lavender.dir/src/apiFetch.cpp.i
.PHONY : src/apiFetch.cpp.i

src/apiFetch.s: src/apiFetch.cpp.s
.PHONY : src/apiFetch.s

# target to generate assembly for a file
src/apiFetch.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lavender.dir/build.make CMakeFiles/lavender.dir/src/apiFetch.cpp.s
.PHONY : src/apiFetch.cpp.s

src/audiofingerprint.o: src/audiofingerprint.cpp.o
.PHONY : src/audiofingerprint.o

# target to build an object file
src/audiofingerprint.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lavender.dir/build.make CMakeFiles/lavender.dir/src/audiofingerprint.cpp.o
.PHONY : src/audiofingerprint.cpp.o

src/audiofingerprint.i: src/audiofingerprint.cpp.i
.PHONY : src/audiofingerprint.i

# target to preprocess a source file
src/audiofingerprint.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lavender.dir/build.make CMakeFiles/lavender.dir/src/audiofingerprint.cpp.i
.PHONY : src/audiofingerprint.cpp.i

src/audiofingerprint.s: src/audiofingerprint.cpp.s
.PHONY : src/audiofingerprint.s

# target to generate assembly for a file
src/audiofingerprint.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lavender.dir/build.make CMakeFiles/lavender.dir/src/audiofingerprint.cpp.s
.PHONY : src/audiofingerprint.cpp.s

src/dbManager.o: src/dbManager.cpp.o
.PHONY : src/dbManager.o

# target to build an object file
src/dbManager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lavender.dir/build.make CMakeFiles/lavender.dir/src/dbManager.cpp.o
.PHONY : src/dbManager.cpp.o

src/dbManager.i: src/dbManager.cpp.i
.PHONY : src/dbManager.i

# target to preprocess a source file
src/dbManager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lavender.dir/build.make CMakeFiles/lavender.dir/src/dbManager.cpp.i
.PHONY : src/dbManager.cpp.i

src/dbManager.s: src/dbManager.cpp.s
.PHONY : src/dbManager.s

# target to generate assembly for a file
src/dbManager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lavender.dir/build.make CMakeFiles/lavender.dir/src/dbManager.cpp.s
.PHONY : src/dbManager.cpp.s

src/introMenu.o: src/introMenu.cpp.o
.PHONY : src/introMenu.o

# target to build an object file
src/introMenu.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lavender.dir/build.make CMakeFiles/lavender.dir/src/introMenu.cpp.o
.PHONY : src/introMenu.cpp.o

src/introMenu.i: src/introMenu.cpp.i
.PHONY : src/introMenu.i

# target to preprocess a source file
src/introMenu.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lavender.dir/build.make CMakeFiles/lavender.dir/src/introMenu.cpp.i
.PHONY : src/introMenu.cpp.i

src/introMenu.s: src/introMenu.cpp.s
.PHONY : src/introMenu.s

# target to generate assembly for a file
src/introMenu.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lavender.dir/build.make CMakeFiles/lavender.dir/src/introMenu.cpp.s
.PHONY : src/introMenu.cpp.s

src/libScan.o: src/libScan.cpp.o
.PHONY : src/libScan.o

# target to build an object file
src/libScan.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lavender.dir/build.make CMakeFiles/lavender.dir/src/libScan.cpp.o
.PHONY : src/libScan.cpp.o

src/libScan.i: src/libScan.cpp.i
.PHONY : src/libScan.i

# target to preprocess a source file
src/libScan.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lavender.dir/build.make CMakeFiles/lavender.dir/src/libScan.cpp.i
.PHONY : src/libScan.cpp.i

src/libScan.s: src/libScan.cpp.s
.PHONY : src/libScan.s

# target to generate assembly for a file
src/libScan.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lavender.dir/build.make CMakeFiles/lavender.dir/src/libScan.cpp.s
.PHONY : src/libScan.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lavender.dir/build.make CMakeFiles/lavender.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lavender.dir/build.make CMakeFiles/lavender.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lavender.dir/build.make CMakeFiles/lavender.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/mainMenu.o: src/mainMenu.cpp.o
.PHONY : src/mainMenu.o

# target to build an object file
src/mainMenu.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lavender.dir/build.make CMakeFiles/lavender.dir/src/mainMenu.cpp.o
.PHONY : src/mainMenu.cpp.o

src/mainMenu.i: src/mainMenu.cpp.i
.PHONY : src/mainMenu.i

# target to preprocess a source file
src/mainMenu.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lavender.dir/build.make CMakeFiles/lavender.dir/src/mainMenu.cpp.i
.PHONY : src/mainMenu.cpp.i

src/mainMenu.s: src/mainMenu.cpp.s
.PHONY : src/mainMenu.s

# target to generate assembly for a file
src/mainMenu.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lavender.dir/build.make CMakeFiles/lavender.dir/src/mainMenu.cpp.s
.PHONY : src/mainMenu.cpp.s

src/mainwindow.o: src/mainwindow.cpp.o
.PHONY : src/mainwindow.o

# target to build an object file
src/mainwindow.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lavender.dir/build.make CMakeFiles/lavender.dir/src/mainwindow.cpp.o
.PHONY : src/mainwindow.cpp.o

src/mainwindow.i: src/mainwindow.cpp.i
.PHONY : src/mainwindow.i

# target to preprocess a source file
src/mainwindow.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lavender.dir/build.make CMakeFiles/lavender.dir/src/mainwindow.cpp.i
.PHONY : src/mainwindow.cpp.i

src/mainwindow.s: src/mainwindow.cpp.s
.PHONY : src/mainwindow.s

# target to generate assembly for a file
src/mainwindow.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lavender.dir/build.make CMakeFiles/lavender.dir/src/mainwindow.cpp.s
.PHONY : src/mainwindow.cpp.s

src/moc_albumMenu.o: src/moc_albumMenu.cpp.o
.PHONY : src/moc_albumMenu.o

# target to build an object file
src/moc_albumMenu.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lavender.dir/build.make CMakeFiles/lavender.dir/src/moc_albumMenu.cpp.o
.PHONY : src/moc_albumMenu.cpp.o

src/moc_albumMenu.i: src/moc_albumMenu.cpp.i
.PHONY : src/moc_albumMenu.i

# target to preprocess a source file
src/moc_albumMenu.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lavender.dir/build.make CMakeFiles/lavender.dir/src/moc_albumMenu.cpp.i
.PHONY : src/moc_albumMenu.cpp.i

src/moc_albumMenu.s: src/moc_albumMenu.cpp.s
.PHONY : src/moc_albumMenu.s

# target to generate assembly for a file
src/moc_albumMenu.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lavender.dir/build.make CMakeFiles/lavender.dir/src/moc_albumMenu.cpp.s
.PHONY : src/moc_albumMenu.cpp.s

src/moc_apiFetch.o: src/moc_apiFetch.cpp.o
.PHONY : src/moc_apiFetch.o

# target to build an object file
src/moc_apiFetch.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lavender.dir/build.make CMakeFiles/lavender.dir/src/moc_apiFetch.cpp.o
.PHONY : src/moc_apiFetch.cpp.o

src/moc_apiFetch.i: src/moc_apiFetch.cpp.i
.PHONY : src/moc_apiFetch.i

# target to preprocess a source file
src/moc_apiFetch.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lavender.dir/build.make CMakeFiles/lavender.dir/src/moc_apiFetch.cpp.i
.PHONY : src/moc_apiFetch.cpp.i

src/moc_apiFetch.s: src/moc_apiFetch.cpp.s
.PHONY : src/moc_apiFetch.s

# target to generate assembly for a file
src/moc_apiFetch.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lavender.dir/build.make CMakeFiles/lavender.dir/src/moc_apiFetch.cpp.s
.PHONY : src/moc_apiFetch.cpp.s

src/moc_audiofingerprint.o: src/moc_audiofingerprint.cpp.o
.PHONY : src/moc_audiofingerprint.o

# target to build an object file
src/moc_audiofingerprint.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lavender.dir/build.make CMakeFiles/lavender.dir/src/moc_audiofingerprint.cpp.o
.PHONY : src/moc_audiofingerprint.cpp.o

src/moc_audiofingerprint.i: src/moc_audiofingerprint.cpp.i
.PHONY : src/moc_audiofingerprint.i

# target to preprocess a source file
src/moc_audiofingerprint.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lavender.dir/build.make CMakeFiles/lavender.dir/src/moc_audiofingerprint.cpp.i
.PHONY : src/moc_audiofingerprint.cpp.i

src/moc_audiofingerprint.s: src/moc_audiofingerprint.cpp.s
.PHONY : src/moc_audiofingerprint.s

# target to generate assembly for a file
src/moc_audiofingerprint.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lavender.dir/build.make CMakeFiles/lavender.dir/src/moc_audiofingerprint.cpp.s
.PHONY : src/moc_audiofingerprint.cpp.s

src/moc_dbManager.o: src/moc_dbManager.cpp.o
.PHONY : src/moc_dbManager.o

# target to build an object file
src/moc_dbManager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lavender.dir/build.make CMakeFiles/lavender.dir/src/moc_dbManager.cpp.o
.PHONY : src/moc_dbManager.cpp.o

src/moc_dbManager.i: src/moc_dbManager.cpp.i
.PHONY : src/moc_dbManager.i

# target to preprocess a source file
src/moc_dbManager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lavender.dir/build.make CMakeFiles/lavender.dir/src/moc_dbManager.cpp.i
.PHONY : src/moc_dbManager.cpp.i

src/moc_dbManager.s: src/moc_dbManager.cpp.s
.PHONY : src/moc_dbManager.s

# target to generate assembly for a file
src/moc_dbManager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lavender.dir/build.make CMakeFiles/lavender.dir/src/moc_dbManager.cpp.s
.PHONY : src/moc_dbManager.cpp.s

src/moc_introMenu.o: src/moc_introMenu.cpp.o
.PHONY : src/moc_introMenu.o

# target to build an object file
src/moc_introMenu.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lavender.dir/build.make CMakeFiles/lavender.dir/src/moc_introMenu.cpp.o
.PHONY : src/moc_introMenu.cpp.o

src/moc_introMenu.i: src/moc_introMenu.cpp.i
.PHONY : src/moc_introMenu.i

# target to preprocess a source file
src/moc_introMenu.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lavender.dir/build.make CMakeFiles/lavender.dir/src/moc_introMenu.cpp.i
.PHONY : src/moc_introMenu.cpp.i

src/moc_introMenu.s: src/moc_introMenu.cpp.s
.PHONY : src/moc_introMenu.s

# target to generate assembly for a file
src/moc_introMenu.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lavender.dir/build.make CMakeFiles/lavender.dir/src/moc_introMenu.cpp.s
.PHONY : src/moc_introMenu.cpp.s

src/moc_libScan.o: src/moc_libScan.cpp.o
.PHONY : src/moc_libScan.o

# target to build an object file
src/moc_libScan.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lavender.dir/build.make CMakeFiles/lavender.dir/src/moc_libScan.cpp.o
.PHONY : src/moc_libScan.cpp.o

src/moc_libScan.i: src/moc_libScan.cpp.i
.PHONY : src/moc_libScan.i

# target to preprocess a source file
src/moc_libScan.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lavender.dir/build.make CMakeFiles/lavender.dir/src/moc_libScan.cpp.i
.PHONY : src/moc_libScan.cpp.i

src/moc_libScan.s: src/moc_libScan.cpp.s
.PHONY : src/moc_libScan.s

# target to generate assembly for a file
src/moc_libScan.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lavender.dir/build.make CMakeFiles/lavender.dir/src/moc_libScan.cpp.s
.PHONY : src/moc_libScan.cpp.s

src/moc_mainMenu.o: src/moc_mainMenu.cpp.o
.PHONY : src/moc_mainMenu.o

# target to build an object file
src/moc_mainMenu.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lavender.dir/build.make CMakeFiles/lavender.dir/src/moc_mainMenu.cpp.o
.PHONY : src/moc_mainMenu.cpp.o

src/moc_mainMenu.i: src/moc_mainMenu.cpp.i
.PHONY : src/moc_mainMenu.i

# target to preprocess a source file
src/moc_mainMenu.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lavender.dir/build.make CMakeFiles/lavender.dir/src/moc_mainMenu.cpp.i
.PHONY : src/moc_mainMenu.cpp.i

src/moc_mainMenu.s: src/moc_mainMenu.cpp.s
.PHONY : src/moc_mainMenu.s

# target to generate assembly for a file
src/moc_mainMenu.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lavender.dir/build.make CMakeFiles/lavender.dir/src/moc_mainMenu.cpp.s
.PHONY : src/moc_mainMenu.cpp.s

src/moc_mainwindow.o: src/moc_mainwindow.cpp.o
.PHONY : src/moc_mainwindow.o

# target to build an object file
src/moc_mainwindow.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lavender.dir/build.make CMakeFiles/lavender.dir/src/moc_mainwindow.cpp.o
.PHONY : src/moc_mainwindow.cpp.o

src/moc_mainwindow.i: src/moc_mainwindow.cpp.i
.PHONY : src/moc_mainwindow.i

# target to preprocess a source file
src/moc_mainwindow.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lavender.dir/build.make CMakeFiles/lavender.dir/src/moc_mainwindow.cpp.i
.PHONY : src/moc_mainwindow.cpp.i

src/moc_mainwindow.s: src/moc_mainwindow.cpp.s
.PHONY : src/moc_mainwindow.s

# target to generate assembly for a file
src/moc_mainwindow.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lavender.dir/build.make CMakeFiles/lavender.dir/src/moc_mainwindow.cpp.s
.PHONY : src/moc_mainwindow.cpp.s

src/moc_playback.o: src/moc_playback.cpp.o
.PHONY : src/moc_playback.o

# target to build an object file
src/moc_playback.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lavender.dir/build.make CMakeFiles/lavender.dir/src/moc_playback.cpp.o
.PHONY : src/moc_playback.cpp.o

src/moc_playback.i: src/moc_playback.cpp.i
.PHONY : src/moc_playback.i

# target to preprocess a source file
src/moc_playback.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lavender.dir/build.make CMakeFiles/lavender.dir/src/moc_playback.cpp.i
.PHONY : src/moc_playback.cpp.i

src/moc_playback.s: src/moc_playback.cpp.s
.PHONY : src/moc_playback.s

# target to generate assembly for a file
src/moc_playback.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lavender.dir/build.make CMakeFiles/lavender.dir/src/moc_playback.cpp.s
.PHONY : src/moc_playback.cpp.s

src/moc_recoMenu.o: src/moc_recoMenu.cpp.o
.PHONY : src/moc_recoMenu.o

# target to build an object file
src/moc_recoMenu.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lavender.dir/build.make CMakeFiles/lavender.dir/src/moc_recoMenu.cpp.o
.PHONY : src/moc_recoMenu.cpp.o

src/moc_recoMenu.i: src/moc_recoMenu.cpp.i
.PHONY : src/moc_recoMenu.i

# target to preprocess a source file
src/moc_recoMenu.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lavender.dir/build.make CMakeFiles/lavender.dir/src/moc_recoMenu.cpp.i
.PHONY : src/moc_recoMenu.cpp.i

src/moc_recoMenu.s: src/moc_recoMenu.cpp.s
.PHONY : src/moc_recoMenu.s

# target to generate assembly for a file
src/moc_recoMenu.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lavender.dir/build.make CMakeFiles/lavender.dir/src/moc_recoMenu.cpp.s
.PHONY : src/moc_recoMenu.cpp.s

src/moc_songMenu.o: src/moc_songMenu.cpp.o
.PHONY : src/moc_songMenu.o

# target to build an object file
src/moc_songMenu.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lavender.dir/build.make CMakeFiles/lavender.dir/src/moc_songMenu.cpp.o
.PHONY : src/moc_songMenu.cpp.o

src/moc_songMenu.i: src/moc_songMenu.cpp.i
.PHONY : src/moc_songMenu.i

# target to preprocess a source file
src/moc_songMenu.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lavender.dir/build.make CMakeFiles/lavender.dir/src/moc_songMenu.cpp.i
.PHONY : src/moc_songMenu.cpp.i

src/moc_songMenu.s: src/moc_songMenu.cpp.s
.PHONY : src/moc_songMenu.s

# target to generate assembly for a file
src/moc_songMenu.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lavender.dir/build.make CMakeFiles/lavender.dir/src/moc_songMenu.cpp.s
.PHONY : src/moc_songMenu.cpp.s

src/playback.o: src/playback.cpp.o
.PHONY : src/playback.o

# target to build an object file
src/playback.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lavender.dir/build.make CMakeFiles/lavender.dir/src/playback.cpp.o
.PHONY : src/playback.cpp.o

src/playback.i: src/playback.cpp.i
.PHONY : src/playback.i

# target to preprocess a source file
src/playback.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lavender.dir/build.make CMakeFiles/lavender.dir/src/playback.cpp.i
.PHONY : src/playback.cpp.i

src/playback.s: src/playback.cpp.s
.PHONY : src/playback.s

# target to generate assembly for a file
src/playback.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lavender.dir/build.make CMakeFiles/lavender.dir/src/playback.cpp.s
.PHONY : src/playback.cpp.s

src/recoMenu.o: src/recoMenu.cpp.o
.PHONY : src/recoMenu.o

# target to build an object file
src/recoMenu.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lavender.dir/build.make CMakeFiles/lavender.dir/src/recoMenu.cpp.o
.PHONY : src/recoMenu.cpp.o

src/recoMenu.i: src/recoMenu.cpp.i
.PHONY : src/recoMenu.i

# target to preprocess a source file
src/recoMenu.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lavender.dir/build.make CMakeFiles/lavender.dir/src/recoMenu.cpp.i
.PHONY : src/recoMenu.cpp.i

src/recoMenu.s: src/recoMenu.cpp.s
.PHONY : src/recoMenu.s

# target to generate assembly for a file
src/recoMenu.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lavender.dir/build.make CMakeFiles/lavender.dir/src/recoMenu.cpp.s
.PHONY : src/recoMenu.cpp.s

src/songMenu.o: src/songMenu.cpp.o
.PHONY : src/songMenu.o

# target to build an object file
src/songMenu.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lavender.dir/build.make CMakeFiles/lavender.dir/src/songMenu.cpp.o
.PHONY : src/songMenu.cpp.o

src/songMenu.i: src/songMenu.cpp.i
.PHONY : src/songMenu.i

# target to preprocess a source file
src/songMenu.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lavender.dir/build.make CMakeFiles/lavender.dir/src/songMenu.cpp.i
.PHONY : src/songMenu.cpp.i

src/songMenu.s: src/songMenu.cpp.s
.PHONY : src/songMenu.s

# target to generate assembly for a file
src/songMenu.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lavender.dir/build.make CMakeFiles/lavender.dir/src/songMenu.cpp.s
.PHONY : src/songMenu.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... lavender"
	@echo "... src/albumMenu.o"
	@echo "... src/albumMenu.i"
	@echo "... src/albumMenu.s"
	@echo "... src/apiFetch.o"
	@echo "... src/apiFetch.i"
	@echo "... src/apiFetch.s"
	@echo "... src/audiofingerprint.o"
	@echo "... src/audiofingerprint.i"
	@echo "... src/audiofingerprint.s"
	@echo "... src/dbManager.o"
	@echo "... src/dbManager.i"
	@echo "... src/dbManager.s"
	@echo "... src/introMenu.o"
	@echo "... src/introMenu.i"
	@echo "... src/introMenu.s"
	@echo "... src/libScan.o"
	@echo "... src/libScan.i"
	@echo "... src/libScan.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/mainMenu.o"
	@echo "... src/mainMenu.i"
	@echo "... src/mainMenu.s"
	@echo "... src/mainwindow.o"
	@echo "... src/mainwindow.i"
	@echo "... src/mainwindow.s"
	@echo "... src/moc_albumMenu.o"
	@echo "... src/moc_albumMenu.i"
	@echo "... src/moc_albumMenu.s"
	@echo "... src/moc_apiFetch.o"
	@echo "... src/moc_apiFetch.i"
	@echo "... src/moc_apiFetch.s"
	@echo "... src/moc_audiofingerprint.o"
	@echo "... src/moc_audiofingerprint.i"
	@echo "... src/moc_audiofingerprint.s"
	@echo "... src/moc_dbManager.o"
	@echo "... src/moc_dbManager.i"
	@echo "... src/moc_dbManager.s"
	@echo "... src/moc_introMenu.o"
	@echo "... src/moc_introMenu.i"
	@echo "... src/moc_introMenu.s"
	@echo "... src/moc_libScan.o"
	@echo "... src/moc_libScan.i"
	@echo "... src/moc_libScan.s"
	@echo "... src/moc_mainMenu.o"
	@echo "... src/moc_mainMenu.i"
	@echo "... src/moc_mainMenu.s"
	@echo "... src/moc_mainwindow.o"
	@echo "... src/moc_mainwindow.i"
	@echo "... src/moc_mainwindow.s"
	@echo "... src/moc_playback.o"
	@echo "... src/moc_playback.i"
	@echo "... src/moc_playback.s"
	@echo "... src/moc_recoMenu.o"
	@echo "... src/moc_recoMenu.i"
	@echo "... src/moc_recoMenu.s"
	@echo "... src/moc_songMenu.o"
	@echo "... src/moc_songMenu.i"
	@echo "... src/moc_songMenu.s"
	@echo "... src/playback.o"
	@echo "... src/playback.i"
	@echo "... src/playback.s"
	@echo "... src/recoMenu.o"
	@echo "... src/recoMenu.i"
	@echo "... src/recoMenu.s"
	@echo "... src/songMenu.o"
	@echo "... src/songMenu.i"
	@echo "... src/songMenu.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

